#### Using correlations in images
- Natural images contain spatial correlations
- For example, pixels along a contour or edge
- How can we use these correlations?

#### What is convolution?

In [4]:
import numpy as np
array = np.array([0, 0, 0 ,0, 0, 1, 1, 1, 1, 1])
kernel = np.array([-1, 1])
conv = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

conv[0] = (kernel * array[0:2]).sum()
conv[1] = (kernel * array[1:3]).sum()
conv[2] = (kernel * array[2:4]).sum()
conv[3] = (kernel * array[3:5]).sum()
conv[4] = (kernel * array[4:6]).sum()
conv[5] = (kernel * array[5:7]).sum()
conv[6] = (kernel * array[6:8]).sum()
conv[7] = (kernel * array[7:9]).sum()
print(conv)


[0 0 0 0 1 0 0 0 0]


In [5]:
for i in range(8):
    conv[i] = (kernel * array[i:i+2]).sum()

conv

array([0, 0, 0, 0, 1, 0, 0, 0, 0])

### Convolution in one dimension

In [6]:
array = np.array([0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0])
kernel = np.array([-1, 1])
conv = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
for ii in range(8):
    conv[ii] = (kernel * array[ii:ii+2]).sum()

conv



array([ 0,  0,  1,  0, -1,  0,  1,  0,  0,  0])

### Two-dimensional convolution

In [7]:
kernel = np.array([[-1, 1],
                   [-1, 1]])

conv = np.zeros((27, 27))
for ii in range(27):
    for jj in range(27):
        window = image[ii:ii+2, jj:jj+2]
        conv[ii, jj] = (kernel * window).sum()

NameError: name 'image' is not defined

### Exercise - One dimension convolutions

In [8]:
array = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])
kernel = np.array([1, -1, 0])
conv = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Output array
for ii in range(8):
    conv[ii] = (kernel * array[ii:ii+3]).sum()

# Print conv
print(conv)

[ 1 -1  1 -1  1 -1  1 -1  0  0]


In [9]:
kernel = np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]])
result = np.zeros(im.shape)

# Output array
for ii in range(im.shape[0] - 3):
    for jj in range(im.shape[1] - 3):
        result[ii, jj] = (im[ii:ii+3, jj:jj+3] *kernel).sum()

# Print result
print(result)

NameError: name 'im' is not defined

### Implementing Convolutions in Keras

- Keras Convolution layer

In [ ]:
from keras.layers import Conv2D
from keras.models import Sequential

Conv2D(10, kernel_size=3, activation="relu")


#### Integrating convolution layers into a network

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
model = Sequential()
model.add(Conv2D(10, kernel_size=3, activation="relu", input_shape=(img_rows, img_cols, 1)))

model.add(Flatten())
model.add(Dense(3, activation="softmax"))

- Fitting a CNN

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

train_data = data.shape

In [ ]:
model.fit(train_data, train_labels, epochs=3, validation_split=0.2)
model.evaluate(test_data, test_labels, epochs=3)

In [ ]:
# Import the necessary components from Keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten

# Initialize the model object
model = Sequential()

# Add a convolutional layer
model.add(Conv2D(10, kernel_size=3, activation='relu', 
               input_shape=(img_rows , img_cols, 1)))

# Flatten the output of the convolutional layer
model.add(Flatten())
# Add an output layer for the 3 categories
model.add(Dense(3, activation='softmax'))

In [ ]:
# Compile the model 
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

# Fit the model on a training set
model.fit(train_data, train_labels, 
          validation_split=0.2, 
          epochs=3, batch_size=10)

In [ ]:
# Evaluate the model on separate test data
model.evaluate(test_data, test_labels, batch_size=10)

#### Tweaking your convolution
- Zero Padding in Keras

In [ ]:
# No Zero Padding is added: default is 'valid' which means no padding is added. The convolutional layer will only be applied to valid positions of the input, resulting in an output that is smaller than the input.
model.add(Conv2D(10, kernel_size=3, activation='relu', input_shape=(img_rows, img_cols, 1)), padding='valid')

In [ ]:
# Zero Padding is added: 'same' means that the convolutional layer will be applied to all positions of the input, including those at the borders. To achieve this, Keras will add zero padding around the input, resulting in an output that has the same spatial dimensions as the input.
model.add(Conv2D(10, kernel_size=3, activation='relu', input_shape=(img_rows, img_cols, 1)), padding='same')

- Strides in Keras

In [ ]:
# Strides: The convolutional layer will be applied to the input with a stride of 1, meaning that the filter will move one pixel at a time across the input. This allows for a more detailed analysis of the input, as the filter will be applied to every possible position of the input.
model.add(Conv2D(10, kernel_size=3, activation='relu', input_shape=(img_rows, img_cols, 1)), strides=1)

In [ ]:
# Strides: The convolutional layer will be applied to the input with a stride of 2, meaning that the filter will move two pixels at a time across the input. This reduces the spatial dimensions of the output and can help to decrease the computational cost.
model.add(Conv2D(10, kernel_size=3, activation='relu', input_shape=(img_rows, img_cols, 1)), strides=2)

- Dilated convolutions

In [ ]:
model.add(Conv2D(10, kernel_size=3, activation='relu', input_shape=(img_rows, img_cols, 1)), dilation_rate=2)

In [ ]:
# Initialize the model
model = Sequential()

# Add the convolutional layer
model.add(Conv2D(10, kernel_size=3, activation='relu', 
              input_shape=(img_rows, img_cols, 1), 
              strides=2))

# Feed into output layer
model.add(Flatten())
model.add(Dense(3, activation='softmax'))